import { archiveGridRaw } from "./archive-grid";
import type { ProjectLink } from "./portfolio";

export type ArchiveCategory =
  | "WORK"
  | "INTERN"
  | "OSS"
  | "FREELANCE"
  | "PERSONAL";

export type ArchiveTier = "STRONG" | "ARCHIVE";

export type ArchiveVerdict =
  | "Strong portfolio"
  | "Use in Leadership / portfolio"
  | "Use in Experience"
  | "Resume candidate"
  | "Portfolio candidate"
  | "Secondary / archive";

export type ArchiveProject = Readonly<{
  id: string;
  idx: string;
  name: string;
  company: string;
  description?: string;
  year: string;
  category: ArchiveCategory;
  tier: ArchiveTier;
  verdict: ArchiveVerdict;
  tags: readonly string[];
  link: string | null;
  links?: readonly ProjectLink[];
  repo: string | null;
  image: string;
  rankScore: number;
}>;

const PLACEHOLDER = "/assets/archive/_placeholder.svg";

// Pre-sorted: STRONG block first (Strong portfolio → Leadership → Experience →
// Resume candidate), then ARCHIVE (Portfolio candidate → Secondary). Within each
// verdict, ordered by Overall score from all_projects_ranked.md, with role-fit
// boost from job_market_ranking.md applied as the first tiebreak.
export const archiveCatalog: Omit<ArchiveProject, "idx">[] = [
  // ────────────────────────────────────────────────────────────────────────
  // STRONG · Strong portfolio (12)
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "postman-clone",
    name: "Postman Clone",
    company: "Personal",
    year: "2024",
    category: "PERSONAL",
    tier: "STRONG",
    verdict: "Strong portfolio",
    tags: ["Next.js", "App Router", "Redux Toolkit", "Saga", "Tailwind"],
    link: "https://github.com/Vinayak1337/postman-clone",
    repo: "https://github.com/Vinayak1337/postman-clone",
    image: PLACEHOLDER,
    rankScore: 9.47,
  },
  {
    id: "bpit-site-redesign",
    name: "BPIT Site Redesign",
    company: "BPIT Tech Team",
    year: "2025",
    category: "WORK",
    tier: "STRONG",
    verdict: "Strong portfolio",
    tags: ["Next.js 15", "Prisma", "MongoDB", "Radix", "Framer Motion", "Three.js"],
    link: "https://bpit-site-redesign.vercel.app/",
    repo: "https://github.com/Vinayak1337/bpit-site-redesign",
    image: "/assets/bpit.webp",
    rankScore: 9.15,
  },
  {
    id: "kmrl-ai-backend",
    name: "KMRL / AI Backend",
    company: "Personal",
    year: "2024",
    category: "PERSONAL",
    tier: "STRONG",
    verdict: "Strong portfolio",
    tags: ["Python", "FastAPI", "LangChain", "Vector store", "Pydantic"],
    link: "https://github.com/Vinayak1337/kmrl-ai-backend",
    repo: "https://github.com/Vinayak1337/kmrl-ai-backend",
    image: PLACEHOLDER,
    rankScore: 9.07,
  },
  {
    id: "bpit-main-site",
    name: "BPIT Main Site (legacy)",
    company: "Site-Tech-Team-BPIT",
    year: "2025",
    category: "WORK",
    tier: "STRONG",
    verdict: "Strong portfolio",
    tags: ["Bootstrap", "MySQL", "Legacy Site"],
    link: "https://github.com/Site-Tech-Team-BPIT/main-site",
    repo: "https://github.com/Site-Tech-Team-BPIT/main-site",
    image: PLACEHOLDER,
    rankScore: 8.97,
  },
  {
    id: "training-and-placement-bpit",
    name: "Training & Placement / BPIT",
    company: "BPIT Tech Team",
    year: "2025",
    category: "WORK",
    tier: "STRONG",
    verdict: "Strong portfolio",
    tags: ["Next.js 15", "Prisma", "Postgres", "NextAuth", "React Query", "Zod"],
    link: "https://github.com/Vinayak1337/training-and-placement-bpit",
    repo: "https://github.com/Vinayak1337/training-and-placement-bpit",
    image: PLACEHOLDER,
    rankScore: 8.82,
  },
  {
    id: "chaintusker-nft-server",
    name: "Chaintusker NFT / Server",
    company: "Freelance",
    year: "2022",
    category: "FREELANCE",
    tier: "STRONG",
    verdict: "Strong portfolio",
    tags: ["Node", "Express", "MongoDB", "Auth", "File uploads"],
    link: "https://github.com/Vinayak1337/chaintusker-nft-server",
    repo: "https://github.com/Vinayak1337/chaintusker-nft-server",
    image: PLACEHOLDER,
    rankScore: 8.78,
  },
  {
    id: "e-commerce-pwa",
    name: "E-Commerce PWA",
    company: "Personal",
    year: "2021",
    category: "PERSONAL",
    tags: ["Express", "MongoDB", "Stripe", "JWT/Argon2", "Swagger", "PWA"],
    tier: "STRONG",
    verdict: "Strong portfolio",
    link: "https://crwn-clothing-pwa.netlify.app/",
    repo: "https://github.com/Vinayak1337/e-commerce-pwa",
    image: "/assets/crwn.webp",
    rankScore: 8.75,
  },
  {
    id: "company-data-scraper",
    name: "Company Data Scraper",
    company: "Personal",
    year: "2022",
    category: "PERSONAL",
    tier: "STRONG",
    verdict: "Strong portfolio",
    tags: ["Python", "Django", "Scraping", "Admin panel", "Dashboard"],
    link: "https://github.com/Vinayak1337/Company-Data-scraper",
    repo: "https://github.com/Vinayak1337/Company-Data-scraper",
    image: PLACEHOLDER,
    rankScore: 8.75,
  },
  {
    id: "picmash-server",
    name: "Picmash / Backend",
    company: "Personal",
    year: "2020",
    category: "PERSONAL",
    tier: "STRONG",
    verdict: "Strong portfolio",
    tags: ["Node", "Express", "MongoDB", "Auth"],
    link: "https://github.com/Vinayak1337/picmash-server",
    repo: "https://github.com/Vinayak1337/picmash-server",
    image: "/assets/picmash-backend.webp",
    rankScore: 8.72,
  },
  {
    id: "kmrl-frontend",
    name: "KMRL / Frontend",
    company: "Personal",
    year: "2024",
    category: "PERSONAL",
    tier: "STRONG",
    verdict: "Strong portfolio",
    tags: ["Next.js", "App Router", "Web Speech API", "Tailwind"],
    link: "https://github.com/Vinayak1337/kmrl-frontend",
    repo: "https://github.com/Vinayak1337/kmrl-frontend",
    image: PLACEHOLDER,
    rankScore: 8.62,
  },
  // ────────────────────────────────────────────────────────────────────────
  // STRONG · Use in Leadership / portfolio (5)
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "relics-audit",
    name: "RelicsAudit",
    company: "Relics Esports",
    year: "2020",
    category: "OSS",
    tier: "STRONG",
    verdict: "Use in Leadership / portfolio",
    tags: ["Node", "Discord.js", "MongoDB", "PM2", "Brawl Stars API"],
    link: "https://github.com/Vinayak1337/RelicsAudit",
    repo: "https://github.com/Vinayak1337/RelicsAudit",
    image: "/assets/relics-audit.webp",
    rankScore: 9.25,
  },
  {
    id: "relics-general",
    name: "Relics General Bot",
    company: "Relics Esports",
    year: "2020",
    category: "OSS",
    tier: "STRONG",
    verdict: "Use in Leadership / portfolio",
    tags: ["Node", "Discord.js", "MongoDB", "Modmail", "Role mgmt"],
    link: "https://github.com/Vinayak1337/relics-general-bot",
    repo: "https://github.com/Vinayak1337/relics-general-bot",
    image: "/assets/relics-general.webp",
    rankScore: 9.05,
  },
  {
    id: "tourney-ticketeer",
    name: "Tourney Ticketeer",
    company: "OSS",
    year: "2020",
    category: "OSS",
    tier: "STRONG",
    verdict: "Use in Leadership / portfolio",
    tags: ["Discord.js", "Node", "Ticketing", "Payments"],
    link: "https://github.com/Vinayak1337/TourneyTicketeer",
    repo: "https://github.com/Vinayak1337/TourneyTicketeer",
    image: "/assets/tourney.webp",
    rankScore: 8.95,
  },
  {
    id: "super-brawl-league",
    name: "Super Brawl League",
    company: "OSS",
    year: "2021",
    category: "OSS",
    tier: "STRONG",
    verdict: "Use in Leadership / portfolio",
    tags: ["Discord.js", "Node", "Modular actions", "Embeds"],
    link: "https://github.com/Vinayak1337/Super-Brawl_League",
    repo: "https://github.com/Vinayak1337/Super-Brawl_League",
    image: PLACEHOLDER,
    rankScore: 7.45,
  },

  // ────────────────────────────────────────────────────────────────────────
  // STRONG · Use in Experience (5)
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "immibot",
    name: "Immibot",
    company: "RemoteHire",
    year: "2024",
    category: "WORK",
    tier: "STRONG",
    verdict: "Use in Experience",
    tags: ["Next.js", "TypeScript", "LangChain", "Flowise", "Prisma", "Stripe", "Clerk"],
    link: "https://nextjsapp-immibot.vercel.app",
    repo: null,
    image: "/assets/immibot.webp",
    rankScore: 9.2,
  },
  {
    id: "wonderlearn-rn",
    name: "wonderLearn (React Native)",
    company: "Wonderhood",
    year: "2023",
    category: "WORK",
    tier: "STRONG",
    verdict: "Use in Experience",
    tags: ["React Native", "Expo", "TypeScript", "Mixpanel", "EAS"],
    link: "https://wonderlearn.app.link/app",
    repo: null,
    image: "/assets/wonderlearn-app.webp",
    rankScore: 8.8,
  },
  {
    id: "wonderhood-next",
    name: "Wonderhood",
    company: "Wonderhood",
    year: "2022",
    category: "WORK",
    tier: "STRONG",
    verdict: "Use in Experience",
    tags: ["Next.js", "TypeScript", "Tailwind", "SCSS", "Shopify"],
    link: "https://wonderhood.in/",
    repo: null,
    image: "/assets/wonderhood.webp",
    rankScore: 8.5,
  },
  {
    id: "wonderlean-rn",
    name: "wonderLean (React Native)",
    company: "Wonderhood",
    year: "2023",
    category: "WORK",
    tier: "STRONG",
    verdict: "Use in Experience",
    tags: ["React Native", "Expo", "TypeScript", "Redux Toolkit", "Saga"],
    link: "https://github.com/Vinayak1337/wonderLean-ReactNative",
    repo: "https://github.com/Vinayak1337/wonderLean-ReactNative",
    image: "/assets/wonderlearn-app.webp",
    rankScore: 7.95,
  },
  {
    id: "mylearning",
    name: "MyLearning",
    company: "Wonderhood",
    year: "2023",
    category: "WORK",
    tier: "STRONG",
    verdict: "Use in Experience",
    tags: ["React", "Vite", "TypeScript", "Redux Toolkit", "Tailwind"],
    link: "https://mylearning.thewonderlearn.com/",
    repo: null,
    image: "/assets/mylearning.webp",
    rankScore: 6.85,
  },

  // ────────────────────────────────────────────────────────────────────────
  // STRONG · Resume candidate (3)
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "ai-chat-vsc-extension",
    name: "AI Chat / VS Code Extension",
    company: "Personal",
    year: "2024",
    category: "PERSONAL",
    tier: "STRONG",
    verdict: "Resume candidate",
    tags: ["TypeScript", "VS Code API", "React webview", "OpenAI", "Gemini", "Webpack"],
    link: "https://github.com/Vinayak1337/AI-chat-vsc-extension",
    repo: "https://github.com/Vinayak1337/AI-chat-vsc-extension",
    image: PLACEHOLDER,
    rankScore: 9.67,
  },
  {
    id: "storefront-nextjs",
    name: "StoreFront / Next.js",
    company: "Personal",
    year: "2024",
    category: "PERSONAL",
    tier: "STRONG",
    verdict: "Resume candidate",
    tags: ["Next.js App Router", "Prisma", "Postgres", "Web Bluetooth", "CSRF/rate-limit"],
    link: "https://github.com/Vinayak1337/StoreFrontNextjs",
    repo: "https://github.com/Vinayak1337/StoreFrontNextjs",
    image: "/assets/storefront-dashboard.webp",
    rankScore: 9.1,
  },
  {
    id: "autism-detector",
    name: "Autism Detector",
    company: "Personal",
    year: "2024",
    category: "PERSONAL",
    tier: "STRONG",
    verdict: "Resume candidate",
    tags: ["Next.js", "TypeScript", "TensorFlow.js", "BlazeFace", "Prisma"],
    link: "https://github.com/Vinayak1337/autism-detector",
    repo: "https://github.com/Vinayak1337/autism-detector",
    image: PLACEHOLDER,
    rankScore: 8.55,
  },

  // ────────────────────────────────────────────────────────────────────────
  // ARCHIVE · Portfolio candidate (34)
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "cadillacs-server",
    name: "Cadillacs / Backend",
    company: "Freelance",
    year: "2022",
    category: "FREELANCE",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["Node", "Express", "MongoDB", "Swagger", "JWT"],
    link: "https://cadillacs-server.onrender.com/docs/",
    repo: "https://github.com/Vinayak1337/cadillacs-server",
    image: "/assets/cadillacs.webp",
    rankScore: 8.57,
  },
  {
    id: "face-recognition-server",
    name: "Face Recognition / Backend",
    company: "Personal",
    year: "2021",
    category: "PERSONAL",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["Express", "MongoDB", "GridFS", "Argon2", "Clarifai API"],
    link: "https://github.com/Vinayak1337/face-recognition-server",
    repo: "https://github.com/Vinayak1337/face-recognition-server",
    image: "/assets/face-backend.webp",
    rankScore: 8.55,
  },
  {
    id: "dating-server",
    name: "Dating App / Backend",
    company: "Possibillion",
    year: "2021",
    category: "INTERN",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["Express", "MongoDB", "Mongoose", "Socket.IO", "S3", "JWT", "Stripe", "Swagger"],
    link: "https://dating-app-server-gdjw.onrender.com/docs",
    repo: "https://github.com/Vinayak1337/dating-app.server",
    image: "/assets/dating-backend.webp",
    rankScore: 8.45,
  },
  {
    id: "books-mgmt-frontend",
    name: "Books Management / Frontend",
    company: "Personal",
    year: "2022",
    category: "PERSONAL",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["React", "TypeScript", "Tables", "CRUD"],
    link: "https://github.com/Vinayak1337/books-management-system.frontend",
    repo: "https://github.com/Vinayak1337/books-management-system.frontend",
    image: PLACEHOLDER,
    rankScore: 8.4,
  },
  {
    id: "bettrhq-flask-react",
    name: "Bettrhq / Flask/React Assessment",
    company: "Bettrhq",
    year: "2023",
    category: "FREELANCE",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["Flask", "React", "Assessment"],
    link: "https://github.com/bettrhq-assessments/flask-react-assessment-Vinayak1337",
    repo: "https://github.com/bettrhq-assessments/flask-react-assessment-Vinayak1337",
    image: PLACEHOLDER,
    rankScore: 8.37,
  },
  {
    id: "storefront-rn-supabase",
    name: "StoreFront (RN/Expo + Supabase)",
    company: "Personal",
    year: "2023",
    category: "PERSONAL",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["React Native", "Expo", "Supabase", "Redux Toolkit", "QR/Print/Haptics"],
    link: "https://github.com/Vinayak1337/StoreFront",
    repo: "https://github.com/Vinayak1337/StoreFront",
    image: "/assets/storefront-dashboard.webp",
    rankScore: 8.35,
  },
  {
    id: "firework-frontend",
    name: "Firework / Frontend",
    company: "Possibillion",
    year: "2021",
    category: "INTERN",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["React", "SASS", "Redux"],
    link: "https://firework-website.netlify.app/",
    repo: "https://github.com/Vinayak1337/firework.frontend",
    image: "/assets/firework-frontend.webp",
    rankScore: 8.3,
  },
  {
    id: "firework-backend",
    name: "Firework / Backend",
    company: "Possibillion",
    year: "2021",
    category: "INTERN",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["Node", "Express", "MongoDB", "FFmpeg", "S3"],
    link: "https://github.com/Vinayak1337/firework.backend",
    repo: "https://github.com/Vinayak1337/firework.backend",
    image: "/assets/firework-backend.webp",
    rankScore: 8.25,
  },
  {
    id: "mteane",
    name: "MTEANE",
    company: "MTEANE",
    year: "2026",
    category: "FREELANCE",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["Fastify", "BullMQ", "Redis", "Postgres", "Zod", "Pino"],
    link: "https://github.com/MTEANE/MTEANE",
    repo: "https://github.com/MTEANE/MTEANE",
    image: PLACEHOLDER,
    rankScore: 8.25,
  },
  {
    id: "picmash-app",
    name: "Picmash / Frontend",
    company: "Personal",
    year: "2020",
    category: "PERSONAL",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["React", "CSS", "JavaScript"],
    link: "https://picmash-app.netlify.app/",
    repo: "https://github.com/Vinayak1337/picmash-app",
    image: "/assets/picmash-frontend.webp",
    rankScore: 8.15,
  },
  {
    id: "wonderlean-next",
    name: "wonderLean (Next.js)",
    company: "Personal",
    year: "2023",
    category: "PERSONAL",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["Next.js", "TypeScript", "Tailwind"],
    link: "https://thewonderlearn.com/",
    repo: "https://github.com/Vinayak1337/wonderLean-next",
    image: "/assets/wonderlearn.webp",
    rankScore: 8.15,
  },
  {
    id: "store-front-rn-prisma",
    name: "Store-Front (RN + Express/Prisma)",
    company: "Personal",
    year: "2023",
    category: "PERSONAL",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["React Native", "Express", "Prisma", "Redux"],
    link: "https://github.com/Vinayak1337/Store-Front",
    repo: "https://github.com/Vinayak1337/Store-Front",
    image: PLACEHOLDER,
    rankScore: 8.15,
  },
  {
    id: "project-manager",
    name: "Project Manager (TS, no framework)",
    company: "Personal",
    year: "2021",
    category: "PERSONAL",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["TypeScript", "DOM", "OOP", "Custom state"],
    link: "https://github.com/Vinayak1337/project-manager",
    repo: "https://github.com/Vinayak1337/project-manager",
    image: PLACEHOLDER,
    rankScore: 8.12,
  },
  {
    id: "robo-app",
    name: "Robo App",
    company: "Personal",
    year: "2020",
    category: "PERSONAL",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["React", "TypeScript", "CSS"],
    link: "https://monsters-rolodex-webapp.netlify.app/",
    repo: "https://github.com/Vinayak1337/robo-app",
    image: "/assets/robo.webp",
    rankScore: 8.05,
  },
  {
    id: "dating-website",
    name: "Dating App / Landing",
    company: "Possibillion",
    year: "2021",
    category: "INTERN",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["React", "SASS", "TypeScript"],
    link: "https://dating-app-website.netlify.app/",
    repo: "https://github.com/Vinayak1337/dating-app.website",
    image: "/assets/dating-landing.webp",
    rankScore: 7.97,
  },
  {
    id: "kmrl-backend",
    name: "KMRL / Backend",
    company: "Personal",
    year: "2024",
    category: "PERSONAL",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["Node", "Express", "REST"],
    link: "https://github.com/Vinayak1337/kmrl-backend",
    repo: "https://github.com/Vinayak1337/kmrl-backend",
    image: PLACEHOLDER,
    rankScore: 7.9,
  },
  {
    id: "books-mgmt-server",
    name: "Books Management / Backend",
    company: "Personal",
    year: "2022",
    category: "PERSONAL",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["Node", "Express", "MongoDB"],
    link: "https://github.com/Vinayak1337/book-management-system.server",
    repo: "https://github.com/Vinayak1337/book-management-system.server",
    image: PLACEHOLDER,
    rankScore: 7.88,
  },
  {
    id: "dukaan-dashboard-ui",
    name: "Dukaan Dashboard UI",
    company: "Personal",
    year: "2022",
    category: "PERSONAL",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["Next.js", "Tailwind", "Dashboard UI"],
    link: "https://github.com/Vinayak1337/dukaan-dashboard-ui",
    repo: "https://github.com/Vinayak1337/dukaan-dashboard-ui",
    image: PLACEHOLDER,
    rankScore: 7.85,
  },
  {
    id: "cup-n-connect",
    name: "Cup-n-Connect",
    company: "Personal",
    year: "2022",
    category: "PERSONAL",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["React", "Node", "Express"],
    link: "https://github.com/Vinayak1337/cup-n-connect",
    repo: "https://github.com/Vinayak1337/cup-n-connect",
    image: PLACEHOLDER,
    rankScore: 7.85,
  },
  {
    id: "cup-n-connect-app",
    name: "Cup-n-Connect / App",
    company: "Personal",
    year: "2022",
    category: "PERSONAL",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["React Native", "Expo"],
    link: "https://github.com/Vinayak1337/cup-n-connect-app",
    repo: "https://github.com/Vinayak1337/cup-n-connect-app",
    image: PLACEHOLDER,
    rankScore: 7.73,
  },
  {
    id: "defithugs",
    name: "DefiThugs",
    company: "Personal",
    year: "2022",
    category: "PERSONAL",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["Web3", "Next.js", "Wallet integration", "NFT"],
    link: "https://github.com/Vinayak1337/DefiThugs",
    repo: "https://github.com/Vinayak1337/DefiThugs",
    image: PLACEHOLDER,
    rankScore: 7.7,
  },
  {
    id: "nutrilife",
    name: "NutriLife",
    company: "Personal",
    year: "2026",
    category: "PERSONAL",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["React Native", "Expo", "Clerk", "Health domain"],
    link: "https://github.com/Vinayak1337/Mealwise",
    links: [
      { label: "GitHub", href: "https://github.com/Vinayak1337/Mealwise" },
      {
        label: "Download APK (v1.0.0)",
        href: "https://github.com/Vinayak1337/Mealwise/releases/tag/v1.0.0",
      },
    ],
    repo: "https://github.com/Vinayak1337/Mealwise",
    image: PLACEHOLDER,
    rankScore: 7.68,
  },
  {
    id: "wonderhood-mylearning-react",
    name: "MyLearning (Wonderhood fork)",
    company: "Wonderhood",
    year: "2023",
    category: "WORK",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["React", "Vite", "TypeScript"],
    link: "https://github.com/Wonderhood/my-learning-react",
    repo: "https://github.com/Wonderhood/my-learning-react",
    image: "/assets/mylearning.webp",
    rankScore: 7.65,
  },
  {
    id: "ghclassroom-accessfix",
    name: "GHClassroom AccessFix",
    company: "Bettrhq",
    year: "2023",
    category: "FREELANCE",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["GitHub Classroom", "Automation", "Access fixes"],
    link: "https://github.com/bettrhq-assessments/GHClassroom.AccessFix",
    repo: "https://github.com/bettrhq-assessments/GHClassroom.AccessFix",
    image: PLACEHOLDER,
    rankScore: 7.6,
  },
  {
    id: "levtours-server",
    name: "LevTours / Backend",
    company: "Possibillion",
    year: "2021",
    category: "INTERN",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["Node", "Express", "MongoDB", "Swagger"],
    link: "https://levtours-server.onrender.com/docs",
    repo: "https://github.com/Vinayak1337/levtours.server",
    image: "/assets/levtours-backend.webp",
    rankScore: 7.6,
  },
  {
    id: "callcoach",
    name: "CallCoach",
    company: "HackSquad-BPIT",
    year: "2025",
    category: "OSS",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["React", "Node", "Hackathon"],
    link: "https://github.com/HackSquad-BPIT/CallCoach",
    repo: "https://github.com/HackSquad-BPIT/CallCoach",
    image: PLACEHOLDER,
    rankScore: 7.6,
  },
  {
    id: "star-wars-dashboard",
    name: "Star Wars Dashboard",
    company: "Personal",
    year: "2021",
    category: "PERSONAL",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["React", "SWAPI", "Dashboard"],
    link: "https://github.com/Vinayak1337/star-wars-dashboard",
    repo: "https://github.com/Vinayak1337/star-wars-dashboard",
    image: PLACEHOLDER,
    rankScore: 7.53,
  },
  {
    id: "chip-component",
    name: "Chip Component",
    company: "Personal",
    year: "2021",
    category: "PERSONAL",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["React", "Component lib"],
    link: "https://github.com/Vinayak1337/chip-component",
    repo: "https://github.com/Vinayak1337/chip-component",
    image: PLACEHOLDER,
    rankScore: 7.5,
  },
  {
    id: "autism-detector-test",
    name: "Autism Detector / Test Harness",
    company: "Personal",
    year: "2024",
    category: "PERSONAL",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["Next.js", "Test fixtures", "TF.js"],
    link: "https://github.com/Vinayak1337/autism-detector-test",
    repo: "https://github.com/Vinayak1337/autism-detector-test",
    image: PLACEHOLDER,
    rankScore: 7.5,
  },
  {
    id: "levtours-website",
    name: "LevTours / Landing",
    company: "Possibillion",
    year: "2021",
    category: "INTERN",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["React", "SASS", "Redux", "TypeScript"],
    link: "https://levtours.netlify.app/",
    repo: "https://github.com/Vinayak1337/levtours.website",
    image: "/assets/levtours-landing.webp",
    rankScore: 7.35,
  },
  {
    id: "movie-upload-server",
    name: "Movie Upload / Backend",
    company: "Personal",
    year: "2021",
    category: "PERSONAL",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["Node", "Express", "MongoDB"],
    link: "https://github.com/Vinayak1337/movie-upload.server",
    repo: "https://github.com/Vinayak1337/movie-upload.server",
    image: PLACEHOLDER,
    rankScore: 7.3,
  },
  {
    id: "visualization-dashboard",
    name: "Visualization Dashboard",
    company: "Personal",
    year: "2021",
    category: "PERSONAL",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["React", "Charts", "Dashboard"],
    link: "https://github.com/Vinayak1337/visualization-dashboard",
    repo: "https://github.com/Vinayak1337/visualization-dashboard",
    image: PLACEHOLDER,
    rankScore: 7.25,
  },
  {
    id: "dating-admin",
    name: "Dating App / Admin",
    company: "Possibillion",
    year: "2021",
    category: "INTERN",
    tier: "ARCHIVE",
    verdict: "Portfolio candidate",
    tags: ["React", "SASS", "Redux"],
    link: "https://dating-app-admin-site.netlify.app",
    repo: "https://github.com/Vinayak1337/dating-app.admin",
    image: "/assets/dating-admin.webp",
    rankScore: 7.15,
  },

  // ────────────────────────────────────────────────────────────────────────
  // ARCHIVE · Secondary / archive (9)
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "pagewrite-ai",
    name: "Pagewrite AI",
    company: "Personal",
    year: "2024",
    category: "PERSONAL",
    tier: "ARCHIVE",
    verdict: "Secondary / archive",
    tags: ["Next.js", "AI writing", "Editor"],
    link: "https://github.com/Vinayak1337/pagewrite-ai",
    repo: "https://github.com/Vinayak1337/pagewrite-ai",
    image: PLACEHOLDER,
    rankScore: 6.9,
  },
  {
    id: "face-recognition-app",
    name: "Face Recognition / Frontend",
    company: "Personal",
    year: "2021",
    category: "PERSONAL",
    tier: "ARCHIVE",
    verdict: "Secondary / archive",
    tags: ["React", "SASS", "Redux"],
    link: "https://face-recognition-ht5h.netlify.app/",
    repo: "https://github.com/Vinayak1337/face-recognition-app",
    image: "/assets/face-frontend.webp",
    rankScore: 6.82,
  },
  {
    id: "unyn",
    name: "Unyn",
    company: "Personal",
    year: "2022",
    category: "PERSONAL",
    tier: "ARCHIVE",
    verdict: "Secondary / archive",
    tags: ["Next.js", "Experimental"],
    link: "https://github.com/Vinayak1337/unyn",
    repo: "https://github.com/Vinayak1337/unyn",
    image: PLACEHOLDER,
    rankScore: 6.8,
  },
  {
    id: "levtours-admin",
    name: "LevTours / Admin",
    company: "Possibillion",
    year: "2021",
    category: "INTERN",
    tier: "ARCHIVE",
    verdict: "Secondary / archive",
    tags: ["React", "SASS", "Redux"],
    link: "https://levtours-admin-panel.netlify.app",
    repo: "https://github.com/Vinayak1337/levtours.admin",
    image: "/assets/levtours-admin.webp",
    rankScore: 6.6,
  },
  {
    id: "candy-crush-mini",
    name: "Candy Crush Mini",
    company: "Personal",
    year: "2020",
    category: "PERSONAL",
    tier: "ARCHIVE",
    verdict: "Secondary / archive",
    tags: ["JavaScript", "Game", "DOM"],
    link: "https://github.com/Vinayak1337/candy-crush-mini",
    repo: "https://github.com/Vinayak1337/candy-crush-mini",
    image: PLACEHOLDER,
    rankScore: 6.4,
  },
  {
    id: "movie-upload-frontend",
    name: "Movie Upload / Frontend",
    company: "Personal",
    year: "2021",
    category: "PERSONAL",
    tier: "ARCHIVE",
    verdict: "Secondary / archive",
    tags: ["React", "Uploader UI"],
    link: "https://github.com/Vinayak1337/movie-upload.frontend",
    repo: "https://github.com/Vinayak1337/movie-upload.frontend",
    image: PLACEHOLDER,
    rankScore: 6.35,
  },
  {
    id: "relics-banhammer",
    name: "Relics Ban Hammer",
    company: "Relics Esports",
    year: "2020",
    category: "OSS",
    tier: "ARCHIVE",
    verdict: "Secondary / archive",
    tags: ["Discord.js", "Node", "Moderation"],
    link: "https://github.com/Vinayak1337/RelicsBanHammer",
    repo: "https://github.com/Vinayak1337/RelicsBanHammer",
    image: "/assets/relics-banhammer.webp",
    rankScore: 6.2,
  },
  {
    id: "pdfy",
    name: "Pdfy",
    company: "Freelance",
    year: "2023",
    category: "FREELANCE",
    tier: "ARCHIVE",
    verdict: "Secondary / archive",
    tags: ["Next.js", "TypeScript", "Tailwind", "PDF"],
    link: "https://pdfy.vercel.app/",
    repo: "https://github.com/Vinayak1337/pdfy",
    image: "/assets/pdfsplitter.webp",
    rankScore: 5.65,
  },
  {
    id: "pdf-splitter",
    name: "PDF Splitter",
    company: "Freelance",
    year: "2022",
    category: "FREELANCE",
    tier: "ARCHIVE",
    verdict: "Secondary / archive",
    tags: ["HTML", "CSS", "JavaScript", "Tailwind"],
    link: "https://pdf-splitter.vercel.app/",
    repo: "https://github.com/Vinayak1337/pdf-splitter",
    image: "/assets/pdfsplitter.webp",
    rankScore: 5.55,
  },
];

const RAW: Omit<ArchiveProject, "idx">[] = archiveGridRaw;

export const archiveProjects: ArchiveProject[] = RAW.map((project, i) => ({
  ...project,
  idx: String(i + 1).padStart(2, "0"),
}));

export const archiveStrong = archiveProjects.filter((p) => p.tier === "STRONG");
export const archiveLongTail = archiveProjects.filter((p) => p.tier === "ARCHIVE");

export const archiveCategories: { id: ArchiveCategory | "ALL"; label: string }[] = [
  { id: "ALL", label: "All" },
  { id: "WORK", label: "Work" },
  { id: "INTERN", label: "Intern" },
  { id: "OSS", label: "OSS" },
  { id: "FREELANCE", label: "Freelance" },
  { id: "PERSONAL", label: "Personal" },
];
