import type { Project } from "./portfolio";

const PLACEHOLDER = "/assets/archive/_placeholder.svg";

export const mainProjectIds = [
  "storefront-nextjs",
  "bpit-site-redesign",
  "immibot",
  "ai-chat-vsc-extension",
  "wonderlearn-react-native",
  "nutrilife",
  "relics-audit",
] as const;

export const portfolioGridProjects: Project[] = [
  {
    id: "nutrilife",
    index: "01",
    name: "NutriLife",
    company: "Personal",
    year: "2026",
    role: "Mobile / Full-stack Product Engineer",
    category: "PERSONAL",
    tags: ["React Native", "Expo", "Clerk", "Redux Saga", "NestJS", "MongoDB"],
    image: "/assets/nutrilife-preview.webp",
    link: "https://github.com/Vinayak1337/NutriLife",
    links: [
      { label: "GitHub", href: "https://github.com/Vinayak1337/NutriLife" },
      {
        label: "Download APK (v1.0.0)",
        href: "https://github.com/Vinayak1337/NutriLife/releases/tag/v1.0.0",
      },
    ],
    blurb:
      "Mobile nutrition app with Clerk auth, onboarding goals, camera food analysis, meal logs, macro tracking, water reminders, calendar, and insights.",
    outcome:
      "A health-domain product prototype that shows React Native architecture across authenticated onboarding, AI-assisted food capture, persisted meal state, nutrition recommendations, and analytics.",
  },
  {
    id: "ai-chat-vsc-extension",
    index: "02",
    name: "AI Chat — VS Code Extension",
    company: "Personal",
    year: "2024",
    role: "AI Tooling Engineer",
    category: "PERSONAL",
    tags: ["TypeScript", "VS Code API", "React webview", "OpenAI", "Gemini"],
    image: "/assets/ai-chat-vscode-agent.webp",
    link: "https://github.com/Vinayak1337/AI-chat-vsc-extension",
    blurb:
      "Local-first VS Code agent workspace with React webview UI, provider switching, project memory, file attachments, and code-write actions.",
    outcome:
      "An editor-native AI workflow that keeps planning, review, debugging, context files, and write-back actions inside the developer workspace.",
  },
  {
    id: "relics-audit",
    index: "03",
    name: "RelicsAudit",
    company: "Relics Esports",
    year: "2020",
    role: "Sole Developer / Org Lead",
    category: "WORK",
    tags: ["Discord.js", "Node", "MongoDB", "Brawl Stars API"],
    image: "/assets/relics-audit.webp",
    link: "https://github.com/Vinayak1337/RelicsAudit",
    blurb:
      "Discord bot for real-time club monitoring, verification, and ladder tracking for the Relics organization.",
    outcome:
      "A Discord operations system that helps gaming communities monitor clubs, rankings, rewards, and player activity at scale.",
  },
  {
    id: "immibot",
    index: "04",
    name: "Immibot",
    company: "RemoteHire",
    year: "2024",
    role: "Full-Stack Engineer",
    category: "WORK",
    tags: ["Next.js", "TypeScript", "LangChain", "Flowise", "Prisma", "Stripe", "Clerk"],
    image: "/assets/immibot.webp",
    link: "https://nextjsapp-immibot.vercel.app",
    blurb:
      "AI immigration assistant with modular country adapters, agentic RAG, adaptive questioning, and weighted eligibility scoring.",
    outcome:
      "An AI immigration advisor that helps applicants understand eligibility, compare pathways, and turn vague questions into structured next steps.",
  },
  {
    id: "bpit-site-redesign",
    index: "05",
    name: "BPIT Site Redesign",
    company: "BPIT Tech Team",
    year: "2025",
    role: "Tech Lead / Institutional Project",
    category: "PERSONAL",
    tags: ["Next.js", "TypeScript", "Tailwind", "MongoDB", "PostHog"],
    image: "/assets/bpit.webp",
    link: "https://bpit-site-redesign.vercel.app/",
    blurb:
      "Official college tech team site built from scratch with an inline click-to-edit CMS for live content updates.",
    outcome:
      "A 2025 institutional project where I led a 3-person build for department publishing, live-page content editing, analytics, and Vercel previews.",
  },
  {
    id: "storefront-nextjs",
    index: "06",
    name: "StoreFrontNextjs",
    company: "Personal",
    year: "2024",
    role: "Product Engineer",
    category: "PERSONAL",
    tags: ["Next.js", "TypeScript", "Prisma", "PostgreSQL", "Thermal Print"],
    image: "/assets/storefront-dashboard.webp",
    link: "https://github.com/Vinayak1337/StoreFrontNextjs",
    blurb:
      "Billing and inventory app with item organization, order creation, analytics, secure sessions, and Bluetooth thermal printing.",
    outcome:
      "A shop operations system that helps small retailers manage orders, inventory, analytics, and receipts from one dashboard.",
  },
  {
    id: "relics-general-bot",
    index: "07",
    name: "Relics General Bot",
    company: "Relics Esports",
    year: "2020",
    role: "Maintainer",
    category: "OSS",
    tags: ["Discord.js", "Node", "MongoDB", "Modmail", "Role mgmt"],
    image: "/assets/relics-general.webp",
    link: "https://github.com/Vinayak1337/relics-general-bot",
    blurb:
      "Modmail, role management, cross-server announcements, and utility commands for Discord communities.",
    outcome:
      "A community management bot that helps Discord teams handle support, announcements, roles, moderation, and daily operations.",
  },
  {
    id: "tourney-ticketeer",
    index: "08",
    name: "TourneyTicketeer",
    company: "Open Source",
    year: "2020",
    role: "Maintainer",
    category: "OSS",
    tags: ["Discord.js", "Node", "Ticketing", "Payments"],
    image: "/assets/tourney.webp",
    link: "https://github.com/Vinayak1337/TourneyTicketeer/",
    blurb:
      "Discord bot for tournament payment ticketing, payment methods, logs, and role assignment.",
    outcome:
      "A tournament operations bot that turns payments, ticketing, and role fulfillment into a repeatable workflow.",
  },
  {
    id: "wonderlearn-react-native",
    index: "09",
    name: "wonderLearn React Native",
    company: "Wonderhood",
    year: "2023",
    role: "SD-1",
    category: "WORK",
    tags: ["React Native", "Expo", "TypeScript", "Redux Toolkit", "Redux Saga"],
    image: "/assets/wonderlearn-app.webp",
    link: "https://wonderlearn.app.link/app",
    blurb:
      "Mobile app for kids aged 2-6 with games, videos, custom players, and resume states after an Ionic to React Native rewrite.",
    outcome:
      "A kids' learning app for guided videos, games, and activities with parent-safe navigation and progress continuity.",
  },
  {
    id: "wonderhood-nextjs",
    index: "10",
    name: "WonderhoodNextJS",
    company: "Wonderhood",
    year: "2022",
    role: "SD-1",
    category: "WORK",
    tags: ["Next.js", "TypeScript", "Tailwind", "Shopify", "SCSS"],
    image: "/assets/wonderlearn.webp",
    link: "https://www.wonderhood.in/",
    blurb:
      "Parent-facing education surface for the wonderLearn ecosystem, rebuilt around a Next.js storefront and content flow.",
    outcome:
      "A parent-facing education platform that explains the learning journey and converts interest into app downloads, plans, and purchases.",
  },
  {
    id: "training-and-placement-bpit",
    index: "11",
    name: "Training & Placement — BPIT",
    company: "BPIT Demo",
    year: "2025",
    role: "Full-stack Engineer",
    category: "PERSONAL",
    tags: ["Next.js", "TypeScript", "Prisma", "Neon", "NextAuth"],
    image: "/assets/training-placement-dashboard.webp",
    link: "https://github.com/Vinayak1337/training-and-placement-bpit",
    blurb:
      "Training and placement dashboard with coordinator and student flows, role-based access, placement drives, applications, and resume uploads.",
    outcome:
      "A placement operations system that shows student records, drive management, application status, and placement analytics in one dashboard.",
  },
  {
    id: "chaintusker-nft-server",
    index: "12",
    name: "Chaintusker NFT Server",
    company: "Freelance",
    year: "2022",
    role: "Freelance",
    category: "FREELANCE",
    tags: ["Node", "Express", "MongoDB", "Auth", "File uploads"],
    image: "/assets/chaintusker-github-repo.webp",
    link: "https://github.com/Vinayak1337/chaintusker-nft-server",
    blurb:
      "Backend for NFT-oriented account, asset, upload, and authentication workflows.",
    outcome:
      "A layered Express/MongoDB API handling accounts, asset uploads, ownership flows, and authentication for an NFT marketplace client.",
  },
  {
    id: "company-data-scraper",
    index: "13",
    name: "Company Data Scraper",
    company: "Personal",
    year: "2022",
    role: "Data Product Engineer",
    category: "PERSONAL",
    tags: ["Python", "Django", "HTMX", "Scraping", "Dashboard"],
    image: "/assets/company-data-scraper-dashboard.webp",
    link: "https://github.com/Vinayak1337/Company-Data-scraper",
    blurb:
      "Django + HTMX job intelligence dashboard that tracks company career pages, normalizes roles, and filters India-first opportunities.",
    outcome:
      "A searchable job pipeline with company tracking, ATS-aware scraping, tech tags, work-mode filters, and direct application links.",
  },
  {
    id: "cadillacs-server",
    index: "14",
    name: "Cadillacs Server",
    company: "Freelance",
    year: "2022",
    role: "Freelance",
    category: "FREELANCE",
    tags: ["Node", "Express", "MongoDB", "Swagger", "JWT"],
    image: "/assets/cadillacs.webp",
    link: "https://cadillacs-server.onrender.com/docs/",
    blurb:
      "Freelance backend API with admin/community routes, JWT auth, persisted content models, and Swagger documentation.",
    outcome:
      "A production-shaped client API with JWT auth, admin and community routes, persisted content models, and live Swagger documentation.",
  },
  {
    id: "autism-detector",
    index: "15",
    name: "Autism Detector",
    company: "Personal",
    year: "2024",
    role: "AI Product Engineer",
    category: "PERSONAL",
    tags: ["Next.js", "TypeScript", "TensorFlow.js", "BlazeFace", "Clerk"],
    image: "/assets/autism-detector-results.svg",
    link: "https://github.com/Vinayak1337/autism-detector",
    blurb:
      "Browser ML prototype for local face/attention tracking, metric capture, and privacy-aware interaction analysis.",
    outcome:
      "An experimental, non-diagnostic AI interface that demonstrates browser-side model integration, consent-led data capture, and metric visualization.",
  },
  {
    id: "face-recognition",
    index: "16",
    name: "Face Recognition",
    company: "Personal",
    year: "2021",
    role: "Personal",
    category: "PERSONAL",
    tags: ["React", "Node", "MongoDB", "Clarifai", "Auth"],
    image: "/assets/face-frontend.webp",
    link: "https://face-recognition-ht5h.netlify.app/",
    links: [
      { label: "Frontend", href: "https://face-recognition-ht5h.netlify.app/" },
      { label: "Backend", href: "https://github.com/Vinayak1337/face-recognition-server" },
    ],
    blurb:
      "Bundled frontend and backend for image upload, face detection, authentication, and usage tracking.",
  },
  {
    id: "dating-app",
    index: "17",
    name: "Dating App",
    company: "Possibillion",
    year: "2021",
    role: "MERN Stack Intern",
    category: "INTERN",
    tags: ["React", "Node", "MongoDB", "Socket.io", "Swagger"],
    image: "/assets/dating-landing.webp",
    link: "https://dating-app-website.netlify.app/",
    links: [
      { label: "Landing", href: "https://dating-app-website.netlify.app/" },
      { label: "Admin", href: "https://dating-app-admin-site.netlify.app" },
      { label: "Backend", href: "https://dating-app-server-gdjw.onrender.com/docs" },
    ],
    blurb:
      "Bundled landing, admin, and backend system for coffee-shop partners, requests, users, and realtime social features.",
  },
  {
    id: "firework",
    index: "18",
    name: "Firework",
    company: "Possibillion",
    year: "2021",
    role: "MERN Stack Intern",
    category: "INTERN",
    tags: ["React", "Node", "MongoDB", "FFmpeg", "S3"],
    image: "/assets/firework-frontend.webp",
    link: "https://firework-website.netlify.app/",
    links: [
      { label: "Frontend", href: "https://firework-website.netlify.app/" },
      { label: "Backend", href: "https://github.com/Vinayak1337/firework.backend" },
    ],
    blurb:
      "Bundled upload product with frontend progress states and a backend that overlays captions with FFmpeg.",
  },
  {
    id: "mteane",
    index: "19",
    name: "MTEANE",
    company: "MTEANE",
    year: "2026",
    role: "Freelance",
    category: "FREELANCE",
    tags: ["Fastify", "BullMQ", "Redis", "Postgres", "Dashboard"],
    image: "/assets/mteane-dashboard.webp",
    link: "https://mteane.vercel.app",
    blurb:
      "Triggrr producer dashboard for event rules, webhook/slack actions, operational health, retries, logs, and dead-letter queue visibility.",
    outcome:
      "A multi-tenant event automation service: define rules that watch incoming events and fire webhooks, emails, or Slack actions, with queues, retries, and DLQ visibility.",
  },
  {
    id: "my-learning-react",
    index: "20",
    name: "my-learning-react",
    company: "Wonderhood",
    year: "2023",
    role: "SD-1",
    category: "WORK",
    tags: ["React", "Vite", "TypeScript", "Redux Toolkit", "Tailwind"],
    image: "/assets/mylearning.webp",
    link: "https://mylearning.thewonderlearn.com/",
    blurb:
      "Teacher dashboard for classroom rosters, per-student video watch percentage, game scores, and module completion.",
    outcome:
      "A classroom learning dashboard that helps teachers track student activity, course progress, assessment reports, and learning outcomes.",
  },
  {
    id: "project-manager",
    index: "21",
    name: "Project Manager",
    company: "Personal",
    year: "2021",
    role: "Personal",
    category: "PERSONAL",
    tags: ["TypeScript", "DOM", "OOP", "Custom state"],
    image: PLACEHOLDER,
    link: "https://github.com/Vinayak1337/project-manager",
    blurb:
      "No-framework TypeScript project management UI exploring typed DOM interactions and custom state.",
  },
  {
    id: "levtours",
    index: "22",
    name: "LevTours",
    company: "Possibillion",
    year: "2021",
    role: "MERN Stack Intern",
    category: "INTERN",
    tags: ["React", "Node", "MongoDB", "Redux", "Swagger"],
    image: "/assets/levtours-landing.webp",
    link: "https://levtours.netlify.app/",
    links: [
      { label: "Landing", href: "https://levtours.netlify.app/" },
      { label: "Admin", href: "https://levtours-admin-panel.netlify.app" },
    ],
    blurb:
      "Bundled tourism platform with landing page, admin dashboard, bookings, blogs, coupons, and backend APIs.",
  },
  {
    id: "e-commerce-pwa",
    index: "23",
    name: "E-Commerce PWA",
    company: "Personal",
    year: "2021",
    role: "Personal",
    category: "PERSONAL",
    tags: ["React", "Redux", "Firebase", "Stripe", "GraphQL"],
    image: "/assets/crwn.webp",
    link: "https://crwn-clothing-pwa.netlify.app/",
    blurb:
      "E-commerce PWA with Google auth, cart, checkout, and Stripe payment flow.",
  },
  {
    id: "star-wars-dashboard",
    index: "24",
    name: "Star Wars Dashboard",
    company: "Personal",
    year: "2021",
    role: "Personal",
    category: "PERSONAL",
    tags: ["React", "SWAPI", "Dashboard"],
    image: PLACEHOLDER,
    link: "https://github.com/Vinayak1337/star-wars-dashboard",
    blurb:
      "Dashboard interface over SWAPI data with list, detail, and browsing patterns.",
  },
  {
    id: "movie-upload",
    index: "25",
    name: "Movie Upload",
    company: "Personal",
    year: "2021",
    role: "Personal",
    category: "PERSONAL",
    tags: ["React", "Node", "Express", "MongoDB", "Uploader"],
    image: PLACEHOLDER,
    link: "https://github.com/Vinayak1337/movie-upload.server",
    links: [
      { label: "Frontend", href: "https://github.com/Vinayak1337/movie-upload.frontend" },
      { label: "Backend", href: "https://github.com/Vinayak1337/movie-upload.server" },
    ],
    blurb:
      "Bundled upload frontend and backend for movie file submission and storage workflows.",
  },
  {
    id: "unyn",
    index: "26",
    name: "Unyn",
    company: "Personal",
    year: "2022",
    role: "Personal",
    category: "PERSONAL",
    tags: ["Next.js", "Experimental", "Product UI"],
    image: PLACEHOLDER,
    link: "https://github.com/Vinayak1337/unyn",
    blurb:
      "Experimental product interface exploring Next.js interaction patterns.",
  },
  {
    id: "kmrl-frontend",
    index: "27",
    name: "KMRL Frontend",
    company: "Personal",
    year: "2024",
    role: "AI Dashboard Prototype",
    category: "AI",
    tags: ["Next.js", "App Router", "RAG", "Gemini", "MongoDB"],
    image: "/assets/kmrl-frontend.webp",
    link: "https://github.com/Vinayak1337/kmrl-frontend",
    blurb:
      "In-progress transit knowledge dashboard with document upload, ingestion status, search, and chat surfaces around KMRL information.",
    outcome:
      "Best kept as WIP proof: dashboard UI, ingestion pipeline thinking, and RAG/chat integration without presenting it as a finished deployment.",
  },
  {
    id: "picmash",
    index: "28",
    name: "Picmash",
    company: "Personal",
    year: "2020",
    role: "Personal",
    category: "PERSONAL",
    tags: ["React", "Node", "Express", "MongoDB", "Auth"],
    image: "/assets/picmash-frontend.webp",
    link: "https://picmash-app.netlify.app/",
    links: [
      { label: "Frontend", href: "https://picmash-app.netlify.app/" },
      { label: "Backend", href: "https://github.com/Vinayak1337/picmash-server" },
    ],
    blurb:
      "Bundled social prototype with frontend feed interactions and backend auth, posts, and image storage.",
  },
  {
    id: "relics-banhammer",
    index: "29",
    name: "RelicsBanHammer",
    company: "Relics Esports",
    year: "2020",
    role: "Maintainer",
    category: "OSS",
    tags: ["Discord.js", "Node", "Moderation"],
    image: "/assets/relics-banhammer.webp",
    link: "https://github.com/Vinayak1337/RelicsBanHammer",
    blurb:
      "Moderation bot for chain bans and unbans across multiple Discord servers.",
  },
  {
    id: "books-management-system",
    index: "30",
    name: "Books Management System",
    company: "Personal",
    year: "2022",
    role: "Personal",
    category: "PERSONAL",
    tags: ["React", "TypeScript", "Node", "Express", "MongoDB"],
    image: PLACEHOLDER,
    link: "https://github.com/Vinayak1337/books-management-system.frontend",
    links: [
      {
        label: "Frontend",
        href: "https://github.com/Vinayak1337/books-management-system.frontend",
      },
      {
        label: "Backend",
        href: "https://github.com/Vinayak1337/book-management-system.server",
      },
    ],
    blurb:
      "Bundled frontend and backend for book records, tables, CRUD workflows, and API-backed management.",
  },
  {
    id: "pdfy",
    index: "31",
    name: "Pdfy",
    company: "Freelance",
    year: "2023",
    role: "Freelance",
    category: "FREELANCE",
    tags: ["Next.js", "TypeScript", "Tailwind", "PDF"],
    image: "/assets/pdfsplitter.webp",
    link: "https://pdfy.vercel.app/",
    blurb:
      "Upload a PDF, view pages, edit metadata on a split-screen interface, and export CSV or modified PDFs.",
  },
  {
    id: "pdf-splitter",
    index: "32",
    name: "PDF Splitter",
    company: "Freelance",
    year: "2022",
    role: "Freelance",
    category: "FREELANCE",
    tags: ["HTML", "CSS", "JavaScript", "Tailwind"],
    image: "/assets/pdfsplitter.webp",
    link: "https://pdf-splitter.vercel.app/",
    blurb:
      "Tool for hand-picking pages or range-selecting pages and downloading split PDFs.",
  },
  {
    id: "postman-clone",
    index: "33",
    name: "Postman Clone",
    company: "Personal",
    year: "2024",
    role: "Developer Tool Prototype",
    category: "PERSONAL",
    tags: ["Next.js", "App Router", "Redux Toolkit", "Saga", "Tailwind"],
    image: "/assets/postman-clone-response-preview.webp",
    link: "https://github.com/Vinayak1337/postman-clone",
    blurb:
      "API client prototype with request-building state, collection-style structure, and Redux/Saga workflow experiments.",
    outcome:
      "An IDE-style API client built on Next.js App Router with complex request-builder state managed through Redux Toolkit and Saga, plus Prisma-backed persistence.",
  },
];
