import type { Project } from "./portfolio";

const PLACEHOLDER = "/assets/archive/_placeholder.svg";

export const mainProjectIds = [
  "immibot",
  "storefront-nextjs",
  "bpit-site-redesign",
  "ai-chat-vsc-extension",
  "wonderlearn-react-native",
  "nutrilife",
  "relics-audit",
] as const;

export const portfolioGridProjects: Project[] = [
  {
    id: "nutrilife",
    index: "01",
    name: "Nutrlife",
    company: "Personal",
    year: "2026",
    role: "Solo build",
    category: "PERSONAL",
    tags: ["React Native", "Expo", "Clerk", "Redux Saga", "NestJS", "MongoDB"],
    image: "/assets/nutrilife-preview.webp",
    link: "https://github.com/Vinayak1337/Nutrlife",
    blurb:
      "Mobile nutrition app with Clerk auth, onboarding goals, camera food analysis, meal logs, macro tracking, water reminders, calendar, and insights.",
    outcome:
      "Snap a photo of a meal and AI logs it for you. It also tracks water, shows your week on a calendar, and installs as an Android app.",
  },
  {
    id: "ai-chat-vsc-extension",
    index: "02",
    name: "AI Chat / VS Code Extension",
    company: "Personal",
    year: "2024",
    role: "Solo build",
    category: "PERSONAL",
    tags: ["TypeScript", "VS Code API", "React webview", "OpenAI", "Gemini"],
    image: "/assets/ai-chat-vscode-agent.webp",
    link: "https://github.com/Vinayak1337/AI-chat-vsc-extension",
    blurb:
      "VS Code AI assistant with React webview UI, provider switching, project memory, file attachments, and code-write actions.",
    outcome:
      "An AI chat that lives inside VS Code. It reads the files you point it at, switches between OpenAI and Gemini, and writes changes straight back into the editor.",
  },
  {
    id: "relics-audit",
    index: "03",
    name: "RelicsAudit",
    company: "Relics Esports",
    year: "2020",
    role: "Community Lead & Bot Builder",
    category: "COMMUNITY",
    tags: ["Discord.js", "Node", "MongoDB", "Brawl Stars API"],
    image: "/assets/relics-audit.webp",
    link: "https://github.com/Vinayak1337/RelicsAudit",
    blurb:
      "Discord bot for real-time club monitoring, verification, and ladder tracking for the Relics organization.",
    outcome:
      "Built for the Relics esports community, which grew to 50,000+ members. It watched club activity, verified members, and tracked ladder standings through the Brawl Stars API.",
  },
  {
    id: "immibot",
    index: "04",
    name: "Immibot",
    company: "RemoteHire",
    year: "2024",
    role: "Full-Stack Engineer",
    category: "WORK",
    tags: ["Next.js", "TypeScript", "Prisma", "Clerk", "Flowise", "PostgreSQL"],
    image: "/assets/immibot.webp",
    link: "https://immibot.vercel.app/",
    blurb:
      "Immigration research assistant with streamed answers from government sources, saved citations, and conversation history across signup.",
    outcome:
      "An immigration research assistant that answers from official Canadian, US, and Australian sources. I built the streamed search with citations, and made guest chats carry over when someone signs up.",
  },
  {
    id: "bpit-site-redesign",
    index: "05",
    name: "BPIT Site Redesign",
    company: "BPIT Tech Team",
    year: "2025",
    role: "Team Lead · BPIT Tech Team",
    category: "INSTITUTIONAL",
    tags: ["Next.js", "TypeScript", "Tailwind", "MongoDB", "PostHog"],
    image: "/assets/bpit.webp",
    link: "https://bpit-site-redesign.vercel.app/",
    blurb:
      "Official college tech team site built from scratch with an inline click-to-edit CMS for live content updates.",
    outcome:
      "I led a team of three to rebuild the college website from scratch. Departments edit their own pages in place, with a preview before anything goes live.",
  },
  {
    id: "storefront-nextjs",
    index: "06",
    name: "StoreFront",
    company: "Personal",
    year: "2024",
    role: "Solo build",
    category: "PERSONAL",
    tags: ["Next.js", "TypeScript", "Prisma", "PostgreSQL", "Thermal Print"],
    image: "/assets/storefront-dashboard.webp",
    link: "https://store-front-nextjs-rho.vercel.app",
    links: [{ label: "GitHub", href: "https://github.com/Vinayak1337/StoreFrontNextjs" }],
    blurb:
      "Billing and inventory app with item organization, order creation, analytics, secure sessions, and Bluetooth thermal printing.",
    outcome:
      "A point-of-sale and inventory app for small shops: take orders, track stock, see what's selling, and print receipts on a Bluetooth thermal printer.",
  },
  {
    id: "relics-general-bot",
    index: "07",
    name: "Relics General Bot",
    company: "Relics Esports",
    year: "2020",
    role: "Maintainer",
    category: "OSS",
    tags: ["Discord.js", "Node", "MongoDB", "Modmail", "Role mgmt"],
    image: "/assets/relics-general.webp",
    link: "https://github.com/Vinayak1337/relics-general-bot",
    blurb:
      "Modmail, role management, cross-server announcements, and utility commands for Discord communities.",
    outcome:
      "The everyday bot for the Relics Discord servers: support tickets through modmail, role management, and announcements across servers.",
  },
  {
    id: "tourney-ticketeer",
    index: "08",
    name: "TourneyTicketeer",
    company: "Open Source",
    year: "2020",
    role: "Maintainer",
    category: "OSS",
    tags: ["Discord.js", "Node", "Ticketing", "Payments"],
    image: "/assets/tourney.webp",
    link: "https://github.com/Vinayak1337/TourneyTicketeer/",
    blurb:
      "Discord bot for tournament payment ticketing, payment methods, logs, and role assignment.",
    outcome:
      "Ran tournament sign-ups on Discord: took payments through tickets, logged them, and handed out roles once a team was confirmed.",
  },
  {
    id: "wonderlearn-react-native",
    index: "09",
    name: "wonderLearn App",
    company: "Wonderhood",
    year: "2023",
    role: "Software Developer I",
    category: "WORK",
    tags: ["React Native", "Expo", "TypeScript", "Redux Toolkit", "Redux Saga"],
    image: "/assets/wonderlearn-app.webp",
    link: "https://wonderlearn.app.link/app",
    blurb:
      "Mobile app for kids aged 2-6 with games, videos, custom players, and resume states after an Ionic to React Native rewrite.",
    outcome:
      "A learning app for kids aged 2 to 6. I led its move from Ionic to React Native and built video and game players that remember where a child left off.",
  },
  {
    id: "wonderhood-nextjs",
    index: "10",
    name: "Wonderhood Website",
    company: "Wonderhood",
    year: "2022",
    role: "Software Developer I",
    category: "WORK",
    tags: ["Next.js", "TypeScript", "Tailwind", "SCSS"],
    image: "/assets/wonderlearn.webp",
    link: "https://www.wonderhood.in/",
    blurb:
      "Parent-facing education surface for the wonderLearn ecosystem, rebuilt around a Next.js storefront and content flow.",
    outcome:
      "A website where parents can browse learning programs, read articles, and access the app and store.",
  },
  {
    id: "training-and-placement-bpit",
    index: "11",
    name: "Training & Placement / BPIT",
    company: "BPIT Demo",
    year: "2025",
    role: "Full-Stack Engineer",
    category: "PERSONAL",
    tags: ["Next.js", "TypeScript", "Prisma", "Neon", "NextAuth"],
    image: "/assets/training-placement-dashboard.webp",
    link: "https://github.com/Vinayak1337/training-and-placement-bpit",
    blurb:
      "Training and placement dashboard with coordinator and student flows, role-based access, placement drives, applications, and resume uploads.",
    outcome:
      "A placement dashboard demo for managing student records, recruitment drives, applications, and placement reports.",
  },
  {
    id: "chaintusker-nft-server",
    index: "12",
    name: "Chaintusker NFT Server",
    company: "Freelance",
    year: "2022",
    role: "Freelance",
    category: "FREELANCE",
    tags: ["Node", "Express", "MongoDB", "Auth", "File uploads"],
    image: "/assets/chaintusker-github-repo.webp",
    link: "https://github.com/Vinayak1337/chaintusker-nft-server",
    blurb:
      "Backend for NFT-oriented account, asset, upload, and authentication workflows.",
    outcome:
      "The API behind an NFT marketplace: accounts, sign-in, asset uploads, and ownership transfers, built on Express and MongoDB.",
  },
  {
    id: "company-data-scraper",
    index: "13",
    name: "Company Data Scraper",
    company: "Personal",
    year: "2022",
    role: "Solo build",
    category: "PERSONAL",
    tags: ["Python", "Django", "HTMX", "Scraping", "Dashboard"],
    image: "/assets/company-data-scraper-dashboard.webp",
    link: "https://github.com/Vinayak1337/Company-Data-scraper",
    blurb:
      "Django + HTMX job intelligence dashboard that tracks company career pages, normalizes roles, and filters India-first opportunities.",
    outcome:
      "Watches company career pages and pulls openings into one searchable board, with filters for tech stack and work mode and a direct link to apply.",
  },
  {
    id: "cadillacs-server",
    index: "14",
    name: "Cadillacs Server",
    company: "Freelance",
    year: "2022",
    role: "Freelance",
    category: "FREELANCE",
    tags: ["Node", "Express", "MongoDB", "Swagger", "JWT"],
    image: "/assets/cadillacs.webp",
    link: "https://cadillacs-server.onrender.com/docs/",
    blurb:
      "Freelance backend API with admin/community routes, JWT auth, persisted content models, and Swagger documentation.",
    outcome:
      "A backend for a client's community app, with JWT sign-in, separate admin and member routes, and Swagger docs for the API.",
  },
  {
    id: "autism-detector",
    index: "15",
    name: "Autism Detector",
    company: "Personal",
    year: "2024",
    role: "AI Product Engineer",
    category: "PERSONAL",
    tags: ["Next.js", "TypeScript", "TensorFlow.js", "BlazeFace", "Clerk"],
    image: "/assets/autism-detector-results.svg",
    link: "https://github.com/Vinayak1337/autism-detector",
    blurb:
      "Browser ML prototype for local face/attention tracking, metric capture, and privacy-aware interaction analysis.",
    outcome:
      "An experimental, non-diagnostic AI interface that demonstrates browser-side model integration, consent-led data capture, and metric visualization.",
  },
  {
    id: "face-recognition",
    index: "16",
    name: "Face Recognition",
    company: "Personal",
    year: "2021",
    role: "Personal project",
    category: "PERSONAL",
    tags: ["React", "Node", "MongoDB", "Clarifai", "Auth"],
    image: "/assets/face-frontend.webp",
    link: "https://face-recognition-ht5h.netlify.app/",
    links: [
      { label: "Frontend", href: "https://face-recognition-ht5h.netlify.app/" },
      { label: "Backend", href: "https://github.com/Vinayak1337/face-recognition-server" },
    ],
    blurb:
      "Bundled frontend and backend for image upload, face detection, authentication, and usage tracking.",
    outcome:
      "Upload a photo and it finds the faces in it using the Clarifai API, with sign-in and a running count of images each user has checked.",
  },
  {
    id: "dating-app",
    index: "17",
    name: "Dating App",
    company: "Possibillion",
    year: "2021",
    role: "MERN Stack Intern",
    category: "INTERN",
    tags: ["React", "Node", "MongoDB", "Socket.io", "Swagger"],
    image: "/assets/dating-landing.webp",
    link: "https://dating-app-website.netlify.app/",
    links: [
      { label: "Landing", href: "https://dating-app-website.netlify.app/" },
      { label: "Admin", href: "https://dating-app-admin-site.netlify.app" },
      { label: "Backend", href: "https://dating-app-server-gdjw.onrender.com/docs" },
    ],
    blurb:
      "Bundled landing, admin, and backend system for coffee-shop partners, requests, users, and realtime social features.",
  },
  {
    id: "firework",
    index: "18",
    name: "Firework",
    company: "Possibillion",
    year: "2021",
    role: "MERN Stack Intern",
    category: "INTERN",
    tags: ["React", "Node", "MongoDB", "FFmpeg", "S3"],
    image: "/assets/firework-frontend.webp",
    link: "https://firework-website.netlify.app/",
    links: [
      { label: "Frontend", href: "https://firework-website.netlify.app/" },
      { label: "Backend", href: "https://github.com/Vinayak1337/firework.backend" },
    ],
    blurb:
      "Bundled upload product with frontend progress states and a backend that overlays captions with FFmpeg.",
  },
  {
    id: "mteane",
    index: "19",
    name: "MTEANE",
    company: "MTEANE",
    year: "2026",
    role: "Freelance",
    category: "FREELANCE",
    tags: ["Fastify", "BullMQ", "Redis", "Postgres", "Dashboard"],
    image: "/assets/mteane-dashboard.webp",
    link: "https://mteane.vercel.app",
    blurb:
      "Triggrr producer dashboard for event rules, webhook/slack actions, operational health, retries, logs, and dead-letter queue visibility.",
    outcome:
      "An event automation service for multiple clients. Set rules on incoming events and it fires webhooks, emails, or Slack messages, with queues, retries, and a view of anything that failed.",
  },
  {
    id: "my-learning-react",
    index: "20",
    name: "my-learning-react",
    company: "Wonderhood",
    year: "2023",
    role: "Software Developer I",
    category: "WORK",
    tags: ["React", "Vite", "TypeScript", "Redux Toolkit", "Tailwind"],
    image: "/assets/mylearning.webp",
    link: null,
    blurb:
      "Teacher dashboard for classroom rosters, per-student video watch percentage, game scores, and module completion.",
    outcome:
      "A classroom learning dashboard that helps teachers track student activity, course progress, assessment reports, and learning outcomes.",
  },
  {
    id: "project-manager",
    index: "21",
    name: "Project Manager",
    company: "Personal",
    year: "2021",
    role: "Personal",
    category: "PERSONAL",
    tags: ["TypeScript", "DOM", "OOP", "Custom state"],
    image: PLACEHOLDER,
    link: "https://github.com/Vinayak1337/project-manager",
    blurb:
      "No-framework TypeScript project management UI exploring typed DOM interactions and custom state.",
  },
  {
    id: "levtours",
    index: "22",
    name: "LevTours",
    company: "Possibillion",
    year: "2021",
    role: "MERN Stack Intern",
    category: "INTERN",
    tags: ["React", "Node", "MongoDB", "Redux", "Swagger"],
    image: "/assets/levtours-landing.webp",
    link: "https://levtours.netlify.app/",
    links: [
      { label: "Landing", href: "https://levtours.netlify.app/" },
      { label: "Admin", href: "https://levtours-admin-panel.netlify.app" },
    ],
    blurb:
      "Bundled tourism platform with landing page, admin dashboard, bookings, blogs, coupons, and backend APIs.",
    outcome:
      "A tourism booking platform from my internship: the public site, an admin dashboard, bookings, blogs, coupons, and the API behind them.",
  },
  {
    id: "e-commerce-pwa",
    index: "23",
    name: "E-Commerce PWA",
    company: "Personal",
    year: "2021",
    role: "Personal project",
    category: "PERSONAL",
    tags: ["React", "Redux", "Firebase", "Stripe", "GraphQL"],
    image: "/assets/crwn.webp",
    link: "https://crwn-clothing-pwa.netlify.app/",
    blurb:
      "E-commerce PWA with Google auth, cart, checkout, and Stripe payment flow.",
    outcome:
      "An installable clothing store with Google sign-in, a cart, and Stripe checkout.",
  },
  {
    id: "star-wars-dashboard",
    index: "24",
    name: "Star Wars Dashboard",
    company: "Personal",
    year: "2021",
    role: "Personal",
    category: "PERSONAL",
    tags: ["React", "SWAPI", "Dashboard"],
    image: PLACEHOLDER,
    link: "https://github.com/Vinayak1337/star-wars-dashboard",
    blurb:
      "Dashboard interface over SWAPI data with list, detail, and browsing patterns.",
  },
  {
    id: "movie-upload",
    index: "25",
    name: "Movie Upload",
    company: "Personal",
    year: "2021",
    role: "Personal",
    category: "PERSONAL",
    tags: ["React", "Node", "Express", "MongoDB", "Uploader"],
    image: PLACEHOLDER,
    link: "https://github.com/Vinayak1337/movie-upload.server",
    links: [
      { label: "Frontend", href: "https://github.com/Vinayak1337/movie-upload.frontend" },
      { label: "Backend", href: "https://github.com/Vinayak1337/movie-upload.server" },
    ],
    blurb:
      "Bundled upload frontend and backend for movie file submission and storage workflows.",
  },
  {
    id: "unyn",
    index: "26",
    name: "Unyn",
    company: "Personal",
    year: "2022",
    role: "Personal",
    category: "PERSONAL",
    tags: ["Next.js", "Experimental", "Product UI"],
    image: PLACEHOLDER,
    link: "https://github.com/Vinayak1337/unyn",
    blurb:
      "Experimental product interface exploring Next.js interaction patterns.",
  },
  {
    id: "kmrl-frontend",
    index: "27",
    name: "KMRL Frontend",
    company: "Personal",
    year: "2024",
    role: "AI Dashboard Prototype",
    category: "AI",
    tags: ["Next.js", "App Router", "RAG", "Gemini", "MongoDB"],
    image: "/assets/kmrl-frontend.webp",
    link: "https://github.com/Vinayak1337/kmrl-frontend",
    blurb:
      "In-progress transit knowledge dashboard with document upload, ingestion status, search, and chat surfaces around KMRL information.",
    outcome:
      "An in-progress prototype for uploading transit documents, tracking ingestion, and searching them through a chat interface.",
  },
  {
    id: "picmash",
    index: "28",
    name: "Picmash",
    company: "Personal",
    year: "2020",
    role: "Personal",
    category: "PERSONAL",
    tags: ["React", "Node", "Express", "MongoDB", "Auth"],
    image: "/assets/picmash-frontend.webp",
    link: "https://picmash-app.netlify.app/",
    links: [
      { label: "Frontend", href: "https://picmash-app.netlify.app/" },
      { label: "Backend", href: "https://github.com/Vinayak1337/picmash-server" },
    ],
    blurb:
      "Bundled social prototype with frontend feed interactions and backend auth, posts, and image storage.",
  },
  {
    id: "relics-banhammer",
    index: "29",
    name: "RelicsBanHammer",
    company: "Relics Esports",
    year: "2020",
    role: "Maintainer",
    category: "OSS",
    tags: ["Discord.js", "Node", "Moderation"],
    image: "/assets/relics-banhammer.webp",
    link: "https://github.com/Vinayak1337/RelicsBanHammer",
    blurb:
      "Moderation bot for chain bans and unbans across multiple Discord servers.",
  },
  {
    id: "books-management-system",
    index: "30",
    name: "Books Management System",
    company: "Personal",
    year: "2022",
    role: "Personal",
    category: "PERSONAL",
    tags: ["React", "TypeScript", "Node", "Express", "MongoDB"],
    image: PLACEHOLDER,
    link: "https://github.com/Vinayak1337/books-management-system.frontend",
    links: [
      {
        label: "Frontend",
        href: "https://github.com/Vinayak1337/books-management-system.frontend",
      },
      {
        label: "Backend",
        href: "https://github.com/Vinayak1337/book-management-system.server",
      },
    ],
    blurb:
      "Bundled frontend and backend for book records, tables, CRUD workflows, and API-backed management.",
  },
  {
    id: "pdfy",
    index: "31",
    name: "Pdfy",
    company: "Freelance",
    year: "2023",
    role: "Freelance",
    category: "FREELANCE",
    tags: ["Next.js", "TypeScript", "Tailwind", "PDF"],
    image: "/assets/pdfsplitter.webp",
    link: "https://pdfy.vercel.app/",
    blurb:
      "Upload a PDF, view pages, edit metadata on a split-screen interface, and export CSV or modified PDFs.",
  },
  {
    id: "pdf-splitter",
    index: "32",
    name: "PDF Splitter",
    company: "Freelance",
    year: "2022",
    role: "Freelance",
    category: "FREELANCE",
    tags: ["HTML", "CSS", "JavaScript", "Tailwind"],
    image: "/assets/pdfsplitter.webp",
    link: "https://pdf-splitter.vercel.app/",
    blurb:
      "Tool for hand-picking pages or range-selecting pages and downloading split PDFs.",
  },
  {
    id: "postman-clone",
    index: "33",
    name: "Postman Clone",
    company: "Personal",
    year: "2024",
    role: "Solo build",
    category: "PERSONAL",
    tags: ["Next.js", "App Router", "Redux Toolkit", "Saga", "Tailwind"],
    image: "/assets/postman-clone-response-preview.webp",
    link: "https://github.com/Vinayak1337/postman-clone",
    blurb:
      "API client prototype with request-building state, collection-style structure, and Redux/Saga workflow experiments.",
    outcome:
      "A lightweight API client for building requests and saving them into collections. Request state runs through Redux Toolkit and Saga, with Prisma for storage.",
  },
];
